// This file is part of CaesarIA.
//
// CaesarIA is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// CaesarIA is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with CaesarIA.  If not, see <http://www.gnu.org/licenses/>.
//
// Copyright 2012-2014 Dalerank, dalerankn8@gmail.com

#ifndef __CAESARIA_BUILDING_PREDEFINITIONS_H_INCLUDED__
#define __CAESARIA_BUILDING_PREDEFINITIONS_H_INCLUDED__

#include "core/predefinitions.hpp"

PREDEFINE_CLASS_SMARTLIST(Building,List)
PREDEFINE_CLASS_SMARTLIST(Factory, List)
PREDEFINE_CLASS_SMARTLIST(ServiceBuilding,List)
PREDEFINE_CLASS_SMARTLIST(Aqueduct,List)
PREDEFINE_CLASS_SMARTLIST(ActorColony,List)
PREDEFINE_CLASS_SMARTLIST(GladiatorSchool,List)
PREDEFINE_CLASS_SMARTLIST(Fountain,List)
PREDEFINE_CLASS_SMARTLIST(Construction,List)
PREDEFINE_CLASS_SMARTLIST(Wharf,List)
PREDEFINE_CLASS_SMARTLIST(Hippodrome,List)
PREDEFINE_CLASS_SMARTLIST(Forum,List)
PREDEFINE_CLASS_SMARTLIST(House,List)
PREDEFINE_CLASS_SMARTLIST(Temple,List)
PREDEFINE_CLASS_SMARTLIST(BigTemple,List)
PREDEFINE_CLASS_SMARTLIST(Theater,List)
PREDEFINE_CLASS_SMARTLIST(Library,List)
PREDEFINE_CLASS_SMARTLIST(School,List)
PREDEFINE_CLASS_SMARTLIST(Academy,List)
PREDEFINE_CLASS_SMARTLIST(WorkingBuilding,List)
PREDEFINE_CLASS_SMARTLIST(Warehouse,List)
PREDEFINE_CLASS_SMARTLIST(Farm,List)
PREDEFINE_CLASS_SMARTLIST(TimberLogger,List)
PREDEFINE_CLASS_SMARTLIST(Wall,List)
PREDEFINE_CLASS_SMARTLIST(Fortification,List)
PREDEFINE_CLASS_SMARTLIST(LionsNursery,List)
PREDEFINE_CLASS_SMARTLIST(Tower,List)
PREDEFINE_CLASS_SMARTLIST(CoastalFactory,List)
PREDEFINE_CLASS_SMARTLIST(Granary,List)
PREDEFINE_CLASS_SMARTLIST(Road,List)
PREDEFINE_CLASS_SMARTLIST(Plaza,List)
PREDEFINE_CLASS_SMARTLIST(Dock,List)
PREDEFINE_CLASS_SMARTLIST(Senate,List)
PREDEFINE_CLASS_SMARTLIST(Shipyard,List)
PREDEFINE_CLASS_SMARTLIST(Ruins,List)
PREDEFINE_CLASS_SMARTLIST(PatrolPoint,List)
PREDEFINE_CLASS_SMARTLIST(Reservoir,List)
PREDEFINE_CLASS_SMARTLIST(Barracks,List)
PREDEFINE_CLASS_SMARTLIST(Creamery,List)
PREDEFINE_CLASS_SMARTLIST(Colosseum,List)
PREDEFINE_CLASS_SMARTLIST(Amphitheater,List)
PREDEFINE_CLASS_SMARTLIST(ConstructionExtension,List)
PREDEFINE_CLASS_SMARTLIST(Fort,List)
PREDEFINE_CLASS_SMARTLIST(Prefecture,List)
PREDEFINE_CLASS_SMARTLIST(Garden,List)
PREDEFINE_CLASS_SMARTLIST(Gatehouse,List)
PREDEFINE_CLASS_SMARTLIST(Market,List)
PREDEFINE_CLASS_SMARTLIST(Well,List)
PREDEFINE_CLASS_SMARTLIST(TempleOracle,List)
PREDEFINE_CLASS_SMARTLIST(Rift,List)
PREDEFINE_CLASS_SMARTLIST(River,List)
PREDEFINE_CLASS_SMARTLIST(NativeField,List)
PREDEFINE_CLASS_SMARTLIST(NativeCenter,List)
PREDEFINE_CLASS_SMARTLIST(NativeHut,List)
PREDEFINE_CLASS_SMARTLIST(Waymark,List)

PREDEFINE_CLASS_SMARTPOINTER(FortArea)


#endif //__CAESARIA_BUILDING_PREDEFINITIONS_H_INCLUDED__
