// This file is part of CaesarIA.
//
// CaesarIA is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// CaesarIA is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with CaesarIA.  If not, see <http://www.gnu.org/licenses/>.

#ifndef __CAESARIA_BUILDING_PREDEFINITIONS_H_INCLUDED__
#define __CAESARIA_BUILDING_PREDEFINITIONS_H_INCLUDED__

#include "core/predefinitions.hpp"

PREDEFINE_CLASS_SMARTPOINTER_LIST(Building,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Factory, List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(ServiceBuilding,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Aqueduct,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(ActorColony,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(GladiatorSchool,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Fountain,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Construction,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Wharf,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Hippodrome,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Forum,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(House,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Temple,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Theater,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Library,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(School,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Academy,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(WorkingBuilding,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Warehouse,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Farm,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(TimberLogger,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Wall,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Fortification,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Fort,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(LionsNursery,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Tower,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(CoastalFactory,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Granary,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Road,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Dock,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Senate,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Shipyard,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Ruins,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(PatrolPoint,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Reservoir,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Barracks,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Creamery,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Colosseum,List)
PREDEFINE_CLASS_SMARTPOINTER_LIST(Amphitheater,List)

PREDEFINE_CLASS_SMARTPOINTER(FortArea)
PREDEFINE_CLASS_SMARTPOINTER(Garden)
PREDEFINE_CLASS_SMARTPOINTER(Market)
PREDEFINE_CLASS_SMARTPOINTER(Well)
PREDEFINE_CLASS_SMARTPOINTER(TempleOracle)
PREDEFINE_CLASS_SMARTPOINTER(Prefecture)

#endif //__CAESARIA_BUILDING_PREDEFINITIONS_H_INCLUDED__
