#!/bin/sh
# Thanks for Anakros from habrahabr.ru
# Run this sript for download dependencies and install game
# then run ./caesaria.macos from console
 
LIBDIR=~/Library/Frameworks/
 
mkdir caesaria
pushd caesaria
 
curl -C - -OL http://downloads.sourceforge.net/project/opencaesar3/bin/caesaria-0.5-macos-build-WRITEHERELASTNUMBER.zip
unzip caesaria-0.5-macos-build-WRITEHERELASTNUMBER.zip
   
sed -i '' s/false/true/ resources/settings.model
chmod +x caesaria.macos && ./caesaria.macos
