#!/bin/sh
# Thanks for Anakros from habrahabr.ru
# Run this sript for download dependencies and install game
# then run ./caesaria.macos from console
 
LIBDIR=~/Library/Frameworks/
 
mkdir caesaria
pushd caesaria
 
curl -C - -OL http://downloads.sourceforge.net/project/opencaesar3/bin/caesaria-mac-b1362.zip
unzip caesaria-mac-b1362.zip
 
curl -O https://www.libsdl.org/release/SDL-1.2.15.dmg
curl -O http://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.dmg
curl -O http://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.dmg
 
hdiutil mount SDL_ttf-2.0.11.dmg
hdiutil mount SDL_mixer-1.2.12.dmg
hdiutil mount SDL-1.2.15.dmg
 
mkdir -p $LIBDIR
cp -r /Volumes/SDL/SDL.framework $LIBDIR
cp -r /Volumes/SDL_mixer/SDL_mixer.framework $LIBDIR
cp -r /Volumes/SDL_ttf/SDL_ttf.framework $LIBDIR
 
sed -i '' s/false/true/ resources/settings.model
chmod +x caesaria.macos && ./caesaria.macos