// This file is part of openCaesar3.
//
// openCaesar3 is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// openCaesar3 is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with openCaesar3.  If not, see <http://www.gnu.org/licenses/>.
//
// Copyright 2012-2013 Gregoire Athanase, gathanase@gmail.com


#ifndef ENUMS_HPP
#define ENUMS_HPP

#include <string>

enum DirectionType 
{ 
  D_NONE, 
  D_NORTH, 
  D_NORTH_WEST, 
  D_WEST, 
  D_SOUTH_WEST, 
  D_SOUTH, 
  D_SOUTH_EAST, 
  D_EAST, 
  D_NORTH_EAST, 
  D_MAX 
};

enum WalkerActionType 
{ 
  WA_NONE, 
  WA_MOVE, 
  WA_FIGHT, 
  WA_DIE, 
  WA_MAX 
};

enum WalkerGraphicType 
{
  WG_NONE, WG_POOR, WG_BATH, WG_PRIEST, WG_ACTOR, WG_TAMER, WG_TAX, WG_CHILD, WG_MARKETLADY, 
  WG_PUSHER, WG_PUSHER2, 
  WG_ENGINEER, 
  WG_GLADIATOR, WG_GLADIATOR2, 
  WG_RIOTER, WG_BARBER, 
  WG_PREFECT, WG_PREFECT_DRAG_WATER, WG_PREFECT_FIGHTS_FIRE,
  WG_HOMELESS, 
  WG_RICH, WG_RICH2,
  WG_DOCTOR, WG_LIBRARIAN, WG_JAVELINEER, 
  WG_SOLDIER, 
  WG_HORSEMAN, WG_HORSE_CARAVAN, WG_CAMEL_CARAVAN, WG_LITTLE_HELPER, 
  WG_MAX 
};

enum WalkerType 
{ 
  WT_NONE, WT_IMMIGRANT, WT_EMIGRANT, 
  WT_SOLDIER, WT_CART_PUSHER, 
  WT_MARKET_BUYER, 
  WT_SERVICE,                     //unknown service
  WT_TRAINEE, WT_WORKERS_HUNTER,
  WT_PREFECT,
  WT_MAX, WT_ALL=WT_MAX 
};

enum GoodType 
{ 
  G_NONE, 
  G_WHEAT, 
  G_FISH, 
  G_MEAT, 
  G_FRUIT, G_VEGETABLE, G_OLIVE, G_OIL, G_GRAPE, G_WINE,
  G_TIMBER, G_FURNITURE, G_CLAY, G_POTTERY, G_IRON, G_WEAPON, G_MARBLE, 
  G_MAX 
};

enum CartTypes {G_SCARB1 = G_MAX, G_SCARB2, CT_MAX };
  
enum ServiceType { 
  S_WELL, S_FOUNTAIN, 
  S_MARKET, 
  S_ENGINEER, 
  S_SENATE, S_FORUM, 
  S_PREFECT, 
  S_TEMPLE_NEPTUNE, S_TEMPLE_CERES, S_TEMPLE_VENUS,  S_TEMPLE_MARS, S_TEMPLE_MERCURE, S_TEMPLE_ORACLE, 
  S_DOCTOR, S_BARBER, S_BATHS, S_HOSPITAL, 
  S_SCHOOL, S_LIBRARY, S_COLLEGE,
  S_THEATER, S_AMPHITHEATER, S_COLLOSSEUM, 
  S_HIPPODROME, 
  S_BURNING_RUINS, 
  S_WORKERS_HUNTER, 
  S_MAX };

enum WaterService { WTR_WELL=0, WTR_FONTAIN, WTR_RESERVOIR, WTR_COUNT };

enum ClimateType { C_CENTRAL, C_NORTHERN, C_DESERT, C_MAX };

// Climate types changes:
// farms productivity, fire rates, fountain radius

enum ScreenType { SCREEN_NONE, SCREEN_MENU, SCREEN_GAME, SCREEN_QUIT, SCREEN_MAX };

enum WalkerTraineeType { WTT_NONE, WTT_ACTOR, WTT_GLADIATOR, WTT_TAMER, WTT_CHARIOT, WTT_MAX };

enum BuildingType
{
   B_NONE,
   B_AMPHITHEATER, B_THEATER, B_HIPPODROME, B_COLLOSSEUM, B_ACTOR, B_GLADIATOR, B_LION, B_CHARIOT,   // entertainment
   B_HOUSE, B_ROAD, B_PLAZA, B_GARDEN,  // road & house
   B_SENATE, B_FORUM,  // administration
   B_GOVERNOR_HOUSE, B_GOVERNOR_VILLA, B_GOVERNOR_PALACE,
   B_RESERVOIR, B_AQUEDUCT, B_FOUNTAIN, B_WELL,  // water
   B_PREFECTURE,   // security
   B_WALL, B_TOWER, B_GATEHOUSE, B_FORT_LEGIONNAIRE, B_FORT_JAVELIN, B_FORT_MOUNTED, B_MILITARY_ACADEMY, B_BARRACKS,  
   B_MARKET, B_GRANARY, B_WAREHOUSE,   // commerce
   B_WHEAT_FARM, B_FRUIT, B_VEGETABLE, B_OLIVE, B_GRAPE, B_MEAT,   // farms
   B_MARBLE, B_IRON_MINE, B_TIMBER, B_CLAY_PIT,   // raw materials
   B_WINE, B_OIL, B_WEAPON, B_FURNITURE, B_POTTERY,  // factories
   B_ENGINEER_POST, B_STATUE1, B_STATUE2, B_STATUE3, B_LOW_BRIDGE, B_HIGH_BRIDGE,  // utility
   B_SHIPYARD, B_DOCK, B_WHARF,
   B_DOCTOR, B_HOSPITAL, B_BATHS, B_BARBER,   // health
   B_SCHOOL, B_COLLEGE, B_LIBRARY, B_MISSION_POST,  // education
   B_TEMPLE_CERES, B_TEMPLE_MARS, B_TEMPLE_NEPTUNE, B_TEMPLE_MERCURE, B_TEMPLE_VENUS, // religion: small temples
   B_BIG_TEMPLE_CERES, B_BIG_TEMPLE_MARS, B_BIG_TEMPLE_NEPTUNE, B_BIG_TEMPLE_MERCURE, B_BIG_TEMPLE_VENUS, // religion: big temples
   B_TEMPLE_ORACLE, // religion: others
   B_NATIVE_HUT, B_NATIVE_CENTER, B_NATIVE_FIELD, // building of natives
   B_TRIUMPHAL_ARCH, 
   B_BURNING_RUINS, B_BURNED_RUINS, B_COLLAPSED_RUINS,
   B_FORUM_2, B_SENATE_2,
   B_MAX
};

enum OverlayType
{
  OV_NOTHING,
  OV_WATER,
  OV_RISK,
  OV_RISK_FIRE,
  OV_RISK_DAMAGE,
  OV_RISK_CRIME,
  OV_RISK_ABORIGEN,
  OV_RISK_TROUBLES,
  OV_ENTERTAINMENT,
  OV_ENTERTAINMENT_ALL,
  OV_ENTERTAINMENT_THEATRES,
  OV_ENTERTAINMENT_AMPHITHEATRES,
  OV_ENTERTAINMENT_COLLISEUM,
  OV_ENTERTAINMENT_HIPPODROME,
  OV_EDUCATION,
  OV_EDUCATION_ALL,
  OV_EDUCATION_SCHOOL,
  OV_EDUCATION_LIBRARY,
  OV_EDUCATION_ACADEMY,
  OV_HEALTH,
  OV_HEALTH_BARBER,
  OV_HEALTH_BATH,
  OV_HEALTH_CLINIC,
  OV_HEALTH_HOSPITAL,
  OV_COMMERCE,
  OV_COMMERCE_TAX,
  OV_COMMERCE_FOOD,
  OV_COMMERCE_PRESTIGE,
  OV_RELIGION,
  OV_COUNT
};

enum BuildMenuType 
{ 
  BM_NONE, 
  BM_WATER, 
  BM_HEALTH, 
  BM_SECURITY, 
  BM_EDUCATION, 
  BM_ENGINEERING, 
  BM_ADMINISTRATION, 
  BM_ENTERTAINMENT, 
  BM_COMMERCE, 
  BM_FARM, 
  BM_RAW_MATERIAL, 
  BM_FACTORY, 
  BM_RELIGION, 
  BM_TEMPLE, 
  BM_BIGTEMPLE, 
  BM_MAX 
};

enum DisasterType
{
    DSTR_BURN,
    DSTR_COLLAPSE,
    DSTR_COUNT
};

enum AdvisorType
{
  ADV_EMPLOYERS=0,
  ADV_LEGION,
  ADV_EMPIRE,
  ADV_RATINGS,
  ADV_TRADING,
  ADV_POPULATION,
  ADV_HEALTH,
  ADV_EDUCATION,
  ADV_ENTERTAINMENT,
  ADV_RELIGION,
  ADV_FINANCE,
  ADV_MAIN,
  ADV_COUNT
} ;

#endif
