{
  etruscanSoldier : {
    nation : "barbarian"
    strike : 3
    resistance : 1
  }

  etruscanArcher : {
    nation : "barbarian"
    strike : 3
    resistance : 1
  }

  romeChastenerSoldier : {
    nation : "rome"
    strike : 3
    resistance : 1
  }

  prefect : {
    nation : "rome"
    strike : 1
    resistance : 0.5
    obsoleteOverlays : [ "gatehouse", "roadBlock" ]
  }

  engineer : {
    nation : "rome"
    obsoleteOverlays : [ "gatehouse", "roadBlock" ]
  }
}
