{
  "##tutorial_text##": "Comenzaremos la concepción de la ciencia upravleniya.\n\n Para empezar a usted tiene que estudiar las bases de la construcción de las colonias romanas. Creen las zonas de la vivienda, y usted veréis, cómo las personas poco tiempo después comenzarán a rellenar su ciudad."
  "##tutorial_prefecture_info ##": "Para la defensa de fuego, construyan la prefectura cerca de la vivienda. La prefectura envía al ciudadano para buscar en el distrito de los obreros. Cuando él pasa de largo cualquier vivienda, prefectura tiene un acceso a la mano de obra. Después de esto puede mandar a los prefectos a la patrulla"
  "##tutorial_prefect_detect_fire##": "Cuando el prefecto descubre el incendio, él comienza a apagarlo por medio del agua de del pozo"
  "##tutorial_ruins_info##": "Usen el capirotazo por el botón derecho del ratón en el lugar del incendio para conocer que se encontraba aquí hasta el incendio. Durante la patrulla regular el prefecto inspecciona el edificio al objeto, bajando el riesgo pozharov.\n los Prefectos pueden servir los edificios dentro de los límites de dos jaulas del camino. \n\n Soobscheniya\n Si usted oiréis las trompetas, entonces a usted ha obrado el mensaje. Para leerlo, presionen el botón con el rollo"
  "##tutorial_engineer_info##": "Aunque el nivel de la construcción en Roma era muy alto, los edificios en el imperio se derrumbaban bastante a menudo. Para evitar esto, construyan en su ciudad el puesto de ingeniería. Él trabaja también, tanto como la prefectura, mandando a los ingenieros patrullar los caminos y reparar cualesquiera daños."
  "##tutorial_engineer_senate##": "Ahora usted puede construir también el senado. En la ciudad él puede ser solamente uno. El senado tiene necesidad de la mano de obra para enviar en la ciudad de los cobradores de los impuestos, que recogen los impuestos de todas las casas, delante de que pasan."
  "##tutorial_religion##": "Sus ciudadanos son religiosos, y aunque que cerca de su vivienda haya unos templos. Debéis dedicar cada templo a un de cinco dioses: a la Venus, la diosa del amor; al Mercurio, el dios de los viajes y el comercio; a Marte, el dios de la guerra; al Ceres, la diosa de la fertilidad; o el Neptuno, el dios del mar. \n\n\n\n\n\n"
  "##tutorial_religion2##": "Traten de construir la cantidad igual de los templos de cada dios. Todos ellos son envidiosos, y pueden, si que los ha privado de la atención. Pueden también, si deciden que su ciudad es bastante grande que en ello haya aún más templos, así que se dirijan por ellos con precaución. Se dirijan al Consejero de la religión para conocer la opinión de los dioses de usted. Los relámpagos hablan sobre lo que el dios desea castigar su ciudad. Más los relámpagos, más fuerte dios o las diosa son enfadadas en usted."
  "##tutorial_collapse_building##": "En los escalones del Senado están las desocupadas. Más tales personas, más arriba nivel del desempleo en su ciudad. \n\n podéis notar, cómo los senderos cerca del Senado se convierten en las sendas pavimentadas. Después de esto los ciudadanos mejoran automáticamente los caminos, también haciendo sus pavimentado."
}